# Generated by Django 4.0.6 on 2023-01-07 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=50, null=True)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('adresse', models.CharField(max_length=50, null=True)),
                ('code_postal', models.CharField(max_length=5, null=True)),
                ('ville', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=13, null=True)),
                ('mail', models.EmailField(max_length=50, null=True, unique=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('disponibilite', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.societe')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('rue1', models.CharField(max_length=50, null=True)),
                ('rue2', models.CharField(max_length=50, null=True)),
                ('code_postal', models.CharField(max_length=5, null=True)),
                ('ville', models.CharField(max_length=50, null=True)),
                ('boite_postale', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.societe')),
            ],
        ),
        migrations.CreateModel(
            name='Details_mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('constitution_equipe', models.BooleanField(default=False, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('heure_debut', models.TimeField(null=True)),
                ('heure_fin', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.client')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipe', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_mission', models.CharField(choices=[('AC', 'Acceptée'), ('RF', 'Refusée'), ('EA', 'En Attente')], default='EA', max_length=10)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('heure_debut', models.TimeField(null=True)),
                ('heure_fin', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.agent')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.client')),
                ('mission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.details_mission')),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.societe')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('site', models.CharField(max_length=50, null=True)),
                ('nature_mission', models.CharField(max_length=250, null=True)),
                ('criteres', models.CharField(max_length=250, null=True)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('heure_debut', models.TimeField(null=True)),
                ('heure_fin', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.client')),
                ('equipe', models.ManyToManyField(through='gestion_activites.Details_mission', to='gestion_activites.equipe')),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.societe')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validite_diplome', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.agent')),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.equipe')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='agents',
            field=models.ManyToManyField(through='gestion_activites.Membership', to='gestion_activites.agent'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='responsable_equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='gestion_activites.agent'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.societe'),
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_diplome', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.societe')),
            ],
        ),
        migrations.AddField(
            model_name='details_mission',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.equipe'),
        ),
        migrations.AddField(
            model_name='details_mission',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.mission'),
        ),
        migrations.AddField(
            model_name='details_mission',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.societe'),
        ),
        migrations.CreateModel(
            name='Details_diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivrance', models.DateField()),
                ('date_expiration', models.DateField()),
                ('validite', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.agent')),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_activites.diplome')),
            ],
        ),
    ]
