# Generated by Django 4.0.6 on 2023-02-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activites', '0002_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_mission',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='details_mission',
            name='inscident',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
