# Generated by Django 4.0.6 on 2023-02-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activites', '0003_details_mission_comment_details_mission_inscident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details_mission',
            old_name='inscident',
            new_name='incident',
        ),
    ]
