# Generated by Django 4.0.6 on 2023-02-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activites', '0004_rename_inscident_details_mission_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_mission',
            name='incident',
            field=models.IntegerField(null=True),
        ),
    ]
