# Generated by Django 4.0.6 on 2023-02-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activites', '0005_alter_details_mission_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation_agent',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
