# Generated by Django 4.0.6 on 2023-02-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activites', '0006_vacation_agent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_mission',
            name='incident',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
