# Generated by Django 4.0.6 on 2023-03-04 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activites', '0008_alter_agent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_mission',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_activites.client'),
        ),
        migrations.AlterField(
            model_name='details_mission',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_activites.equipe'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_activites.agent'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_activites.client'),
        ),
        migrations.AlterField(
            model_name='vacation_agent',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_activites.agent'),
        ),
        migrations.AlterField(
            model_name='vacation_agent',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_activites.client'),
        ),
    ]
