# Generated by Django 4.0.6 on 2023-03-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activites', '0009_alter_details_mission_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation_agent',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_activites.agent'),
        ),
    ]
