# Generated by Django 4.0.6 on 2023-03-05 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activites', '0011_alter_vacation_agent_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation_agent',
            name='agent',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='gestion_activites.agent'),
        ),
    ]
