# Generated by Django 4.0.6 on 2023-02-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnalites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detailsfonctionnalites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valide', models.BooleanField(default=False)),
                ('date_delivrance', models.DateField()),
                ('date_expiration', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.fonctionnalites')),
                ('societe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateurs.societe')),
            ],
        ),
    ]
